# Generated by Django 4.1 on 2022-09-28 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
    ]
